#define NISEC_VENDOR_NSS 0x4E534543 /* NSEC */

#define CKM_NISEC (CKM_VENDOR_DEFINED | NISEC_VENDOR_NSS)
#define CKP_NISEC (CKP_VENDOR_DEFINED | NISEC_VENDOR_NSS)
#define CKK_NISEC (CKK_VENDOR_DEFINED | NISEC_VENDOR_NSS)

// Ml-DSA key types
#define CKK_ML_DSA (CKK_NISEC + 1)

// Ml-DSA mechanism types
#define CKM_ML_DSA_KEYGEN (CKM_NISEC + 2)
#define CKM_ML_DSA (CKM_NISEC + 3)
